services:
  - type: web
    name: afiyi-wellness
    env: php
    region: frankfurt
    plan: free
    buildCommand: "composer install --no-dev --optimize-autoloader && npm install && npm run build && touch database/database.sqlite && php artisan migrate --force"
    startCommand: "php artisan serve --host 0.0.0.0 --port $PORT"
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_URL
        value: https://afiyi-wellness.onrender.com
      - key: DB_CONNECTION
        value: sqlite
      - key: DB_DATABASE
        value: /opt/render/project/src/database/database.sqlite
      - key: APP_KEY
        generateValue: true
